In [1]:
import json

# Corrected JSON data
corrected_json_data = {
    "session_name": "test",
    "session_description": "test",
    "design_state_data": {
        "session_info": {
            "project_id": "1",
            "experiment_id": "kkkk-11",
            "dataset": "iris_modified.csv",
            "session_name": "test",
            "session_description": "test"
        },
        "target": {
            "prediction_type": "Classification",
            "target": "species",
            "type": "classification",
            "partitioning": True
        },
        "train": {
            "policy": "Split the dataset",
            "time_variable": "sepal_length",
            "sampling_method": "No sampling(whole data)",
            "split": "Randomly",
            "k_fold": False,
            "train_ratio": 0.8,
            "random_seed": 10
        },
        "feature_handling": {
            "sepal_length": {
                "feature_name": "sepal_length",
                "is_selected": True,
                "feature_variable_type": "numerical",
                "feature_details": {
                    "numerical_handling": "Keep as regular numerical feature",
                    "rescaling": "No rescaling",
                    "make_derived_feats": False,
                    "missing_values": "Impute",
                    "impute_with": "Average of values"
                }
            },
            "sepal_width": {
                "feature_name": "sepal_width",
                "is_selected": True,
                "feature_variable_type": "numerical",
                "feature_details": {
                    "numerical_handling": "Keep as regular numerical feature",
                    "rescaling": "No rescaling",
                    "make_derived_feats": False,
                    "missing_values": "Impute",
                    "impute_with": "Average of values"
                }
            },
            "petal_length": {
                "feature_name": "petal_length",
                "is_selected": True,
                "feature_variable_type": "numerical",
                "feature_details": {
                    "numerical_handling": "Keep as regular numerical feature",
                    "rescaling": "No rescaling",
                    "make_derived_feats": False,
                    "missing_values": "Impute",
                    "impute_with": "Average of values"
                }
            },
            "petal_width": {
                "feature_name": "petal_width",
                "is_selected": False,
                "feature_variable_type": "numerical",
                "feature_details": {
                    "numerical_handling": "Keep as regular numerical feature",
                    "rescaling": "No rescaling",
                    "make_derived_feats": False,
                    "missing_values": "Impute",
                    "impute_with": "Average of values"
                }
            },
            "species": {
                "feature_name": "species",
                "is_selected": True,
                "feature_variable_type": "text",
                "feature_details": {
                    "text_handling": "Tokenize and hash",
                    "hash_columns": 0
                }
            }
        },
        "algorithms": {
            "RandomForestClassifier": {
                "model_name": "Random Forest Classifier",
                "is_selected": True,
                "min_trees": 10,
                "max_trees": 30,
                "feature_sampling_statergy": "Default",
                "min_depth": 20,
                "max_depth": 30,
                "min_samples_per_leaf_min_value": 5,
                "min_samples_per_leaf_max_value": 50,
                "parallelism": 0
            },
            "RandomForestRegressor": {
                "model_name": "Random Forest Regressor",
                "is_selected": False,
                "min_trees": 10,
                "max_trees": 20,
                "feature_sampling_statergy": "Default",
                "min_depth": 20,
                "max_depth": 25,
                "min_samples_per_leaf_min_value": 5,
                "min_samples_per_leaf_max_value": 10,
                "parallelism": 0
            },
            "LinearRegression": {
                "model_name": "LinearRegression",
                "is_selected": False,
                "parallelism": 2,
                "min_iter": 30,
                "max_iter": 50,
                "min_regparam": 0.5,
                "max_regparam": 0.8,
                "min_elasticnet": 0.5,
                "max_elasticnet": 0.8
            },
            "LogisticRegression": {
                "model_name": "LogisticRegression",
                "is_selected": False,
                "parallelism": 2,
                "min_iter": 30,
                "max_iter": 50,
                "min_regparam": 0.5,
                "max_regparam": 0.8,
                "min_elasticnet": 0.5,
                "max_elasticnet": 0.8
            },
            "RidgeRegression": {
                "model_name": "RidgeRegression",
                "is_selected": False,
                "regularization_term": "Specify values to test",
                "min_iter": 30,
                "max_iter": 50,
                "min_regparam": 0.5,
                "max_regparam": 0.8
            },
            "LassoRegression": {
                "model_name": "Lasso Regression",
                "is_selected": False,
                "regularization_term": "Specify values to test",
                "min_iter": 30,
                "max_iter": 50,
                "min_regparam": 0.5,
                "max_regparam": 0.8
            },
            "ElasticNetRegression": {
                "model_name": "Lasso Regression",
                "is_selected": False,
                "regularization_term": "Specify values to test",
                "min_iter": 30,
                "max_iter": 50,
                "min_regparam": 0.5,
                "max_regparam": 0.8,
                "min_elasticnet": 0.5,
                "max_elasticnet": 0.8
            },
            "xg_boost": {
                "model_name": "XG Boost",
                "is_selected": False,
                "use_gradient_boosted_tree": True,
                "dart": True,
                "tree_method": "",
                "random_state": 0,
                "max_num_of_trees": 0,
                "early_stopping": True,
                "early_stopping_rounds": 2,
                "max_depth_of_tree": [56, 89],
                "learningRate": [89, 76],
                "l1_regularization": [77],
                "l2_regularization": [78],
                "gamma": [68],
                "min_child_weight": [67],
                "sub_sample": [67],
                "col_sample_by_tree": [67],
                "replace_missing_values": False,
                "parallelism": 0
            },
            "DecisionTreeRegressor": {
                "model_name": "Decision Tree",
                "is_selected": False,
                "min_depth": 4,
                "max_depth": 7,
                "use_gini": False,
                "use_entropy": True,
                "min_samples_per_leaf": [12, 6],
                "use_best": True,
                "use_random": True
            },
            "DecisionTreeClassifier": {
                "model_name": "Decision Tree",
                "is_selected": True,
                "min_depth": 4,
                "max_depth": 7,
                "use_gini": False,
                "use_entropy": True,
                "min_samples_per_leaf": [12, 6],
                "use_best": True,
                "use_random": False
            },
            "SVM": {
                "model_name": "Support Vector Machine",
                "is_selected": False,
                "linear_kernel": True,
                "rep_kernel": True,
                "polynomial_kernel": True,
                "sigmoid_kernel": True,
                "c_value": [566, 79],
                "auto": True,
                "scale": True,
                "custom_gamma_values": True,
                "tolerance": 7,
                "max_iterations": 7
            },
            "KNN": {
                "model_name": "KNN",
                "is_selected": False,
                "k_value": [78],
                "distance_weighting": True,
                "neighbour_finding_algorithm": "Automatic",
                "random_state": 0,
                "p_value": 0
            },
            "neural_network": {
                "model_name": "Neural Network",
                "is_selected": False,
                "hidden_layer_sizes": [67, 89],
                "activation": "",
                "alpha_value": 0,
                "max_iterations": 0,
                "convergence_tolerance": 0,
                "early_stopping": True,
                "solver": "ADAM",
                "shuffle_data": True,
                "initial_learning_rate": 0,
                "automatic_batching": True,
                "beta_1": 0,
                "beta_2": 0,
                "epsilon": 0,
                "power_t": 0,
                "momentum": 0,
                "use_nesterov_momentum": False
            }
        }
    }
}

corrected_json_string = json.dumps(corrected_json_data)

with open("corrected_algoparams.json", "w") as file:
    file.write(corrected_json_string)


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Preprocessing
def preprocess_data(X_train, X_test):
    # 1. Impute missing values
    imputer = SimpleImputer(strategy="mean")
    X_train_imputed = imputer.fit_transform(X_train)
    X_test_imputed = imputer.transform(X_test)
    
    #  Standardize features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_imputed)
    X_test_scaled = scaler.transform(X_test_imputed)
    
    return X_train_scaled, X_test_scaled


# Split the Data
def split_data(dataset, target_variable, test_size, random_seed):
    X = dataset.drop(columns=[target_variable])
    y = dataset[target_variable]
    return train_test_split(X, y, test_size=test_size, random_state=random_seed)



In [3]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.svm import SVC, SVR
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.neural_network import MLPClassifier, MLPRegressor
import xgboost as xgb
import pandas as pd
import numpy as np
import json

# Load your corrected JSON data
with open("corrected_algoparams.json", "r") as file:
    corrected_json_data = json.load(file)

# Load your dataset, for example, using pandas
dataset = pd.read_csv(corrected_json_data["design_state_data"]["session_info"]["dataset"])

# Separate features and target
X = dataset.drop(columns=[corrected_json_data["design_state_data"]["target"]["target"]])
y = dataset[corrected_json_data["design_state_data"]["target"]["target"]]

# Iterate over algorithms and train models
for algo_name, algo_params in corrected_json_data["design_state_data"]["algorithms"].items():
    if algo_params["is_selected"]:
        print(f"Training model: {algo_params['model_name']}")

        if algo_name == "RandomForestClassifier":
            model = RandomForestClassifier(
                n_estimators=np.random.randint(algo_params["min_trees"], algo_params["max_trees"] + 1),
                min_samples_leaf=np.random.randint(algo_params["min_samples_per_leaf_min_value"],
                                                     algo_params["min_samples_per_leaf_max_value"] + 1),
                max_depth=np.random.randint(algo_params["min_depth"], algo_params["max_depth"] + 1),
                n_jobs=-1 if algo_params["parallelism"] == 0 else algo_params["parallelism"]  # Set to -1 for auto parallelism
            )
        elif algo_name == "RandomForestRegressor":
            model = RandomForestRegressor(
                n_estimators=np.random.randint(algo_params["min_trees"], algo_params["max_trees"] + 1),
                min_samples_leaf=np.random.randint(algo_params["min_samples_per_leaf_min_value"],
                                                     algo_params["min_samples_per_leaf_max_value"] + 1),
                max_depth=np.random.randint(algo_params["min_depth"], algo_params["max_depth"] + 1),
                n_jobs=-1 if algo_params["parallelism"] == 0 else algo_params["parallelism"]  # Set to -1 for auto parallelism
            )
        elif algo_name == "LinearRegression":
            model = LinearRegression(
                n_jobs=-1 if algo_params["parallelism"] == 0 else algo_params["parallelism"]  # Set to -1 for auto parallelism
            )

        # Train the model
        model.fit(X, y)

print("Training complete.")


Training model: Random Forest Classifier
Training model: Decision Tree
Training complete.


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, r2_score

# Load your corrected JSON data
with open("corrected_algoparams.json", "r") as file:
    corrected_json_data = json.load(file)

# Load your dataset, for example, using pandas
dataset = pd.read_csv(corrected_json_data["design_state_data"]["session_info"]["dataset"])

# Separate features and target
X = dataset.drop(columns=[corrected_json_data["design_state_data"]["target"]["target"]])
y = dataset[corrected_json_data["design_state_data"]["target"]["target"]]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # Adjust test_size as needed

# Iterate over algorithms and train models
for algo_name, algo_params in corrected_json_data["design_state_data"]["algorithms"].items():
    if algo_params["is_selected"]:
        print(f"Training model: {algo_params['model_name']}")


        # Train the model
        model.fit(X_train, y_train)

        # Evaluate the model
        if algo_params["model_name"] in ["Random Forest Classifier", "Decision Tree"]:
            # For classification tasks
            y_pred = model.predict(X_test)

            # Calculate accuracy
            accuracy = accuracy_score(y_test, y_pred)
            print("Accuracy:", accuracy)

            # Generate classification report
            print("Classification Report:")
            print(classification_report(y_test, y_pred))

            # Generate confusion matrix
            print("Confusion Matrix:")
            print(confusion_matrix(y_test, y_pred))
        elif algo_params["model_name"] in ["Random Forest Regressor", "Linear Regression"]:
            # For regression tasks
            y_pred = model.predict(X_test)

            # Calculate mean squared error
            mse = mean_squared_error(y_test, y_pred)
            print("Mean Squared Error:", mse)

            # Calculate R-squared
            r2 = r2_score(y_test, y_pred)
            print("R-squared:", r2)

print("Training and evaluation complete.")


Training model: Random Forest Classifier
Accuracy: 1.0
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Training model: Decision Tree
Accuracy: 1.0
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        

In [5]:
from sklearn.preprocessing import LabelEncoder

# Load your corrected JSON data
with open("corrected_algoparams.json", "r") as file:
    corrected_json_data = json.load(file)

# Load your dataset, for example, using pandas
dataset = pd.read_csv(corrected_json_data["design_state_data"]["session_info"]["dataset"])

# Separate features and target
X = dataset.drop(columns=[corrected_json_data["design_state_data"]["target"]["target"]])
y = dataset[corrected_json_data["design_state_data"]["target"]["target"]]

# Encode the target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # Adjust test_size as needed

# Iterate over algorithms and train models
for algo_name, algo_params in corrected_json_data["design_state_data"]["algorithms"].items():
    if algo_params["is_selected"]:
        print(f"Training model: {algo_params['model_name']}")

        # Train the model
        model.fit(X_train, y_train)

        # Evaluate the model
        # For classification tasks
        y_pred = model.predict(X_test)

        # Calculate accuracy
        accuracy = accuracy_score(y_test, y_pred)
        print("Accuracy:", accuracy)

        # Generate classification report
        print("Classification Report:")
        print(classification_report(y_test, y_pred))

        # Generate confusion matrix
        print("Confusion Matrix:")
        print(confusion_matrix(y_test, y_pred))

print("Training and evaluation complete.")


Training model: Random Forest Classifier
Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Training model: Decision Tree
Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9 

In [6]:
from sklearn.metrics import mean_squared_error, r2_score

# Assuming you have a test set X_test and y_test

# Make predictions
y_pred = model.predict(X_test)

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Calculate R-squared
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)


Mean Squared Error: 0.0
R-squared: 1.0
